// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY2XIk04sdn92yIfjD-koZwCAwklhs54Y',
    appId: '1:36599770480:web:c998b6589ae9e92ef833b5',
    messagingSenderId: '36599770480',
    projectId: 'chatline-6b819',
    authDomain: 'chatline-6b819.firebaseapp.com',
    storageBucket: 'chatline-6b819.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu6sid9kCK-s8R_4MargISyQV-v-T1C-A',
    appId: '1:36599770480:android:1f268649cc0ac4ddf833b5',
    messagingSenderId: '36599770480',
    projectId: 'chatline-6b819',
    storageBucket: 'chatline-6b819.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8khl-Aei2_5OyRXbi1J6WBvbVSgDPicg',
    appId: '1:36599770480:ios:38b18ef606234f26f833b5',
    messagingSenderId: '36599770480',
    projectId: 'chatline-6b819',
    storageBucket: 'chatline-6b819.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8khl-Aei2_5OyRXbi1J6WBvbVSgDPicg',
    appId: '1:36599770480:ios:38b18ef606234f26f833b5',
    messagingSenderId: '36599770480',
    projectId: 'chatline-6b819',
    storageBucket: 'chatline-6b819.appspot.com',
    iosBundleId: 'com.example.testProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCY2XIk04sdn92yIfjD-koZwCAwklhs54Y',
    appId: '1:36599770480:web:5f3b892e3a278a23f833b5',
    messagingSenderId: '36599770480',
    projectId: 'chatline-6b819',
    authDomain: 'chatline-6b819.firebaseapp.com',
    storageBucket: 'chatline-6b819.appspot.com',
  );
}
